### ISSUE TITLE
Paying is not redirecting

### ISSUE THREAD

**Issue by jxltom** [jxltom/saleor#7]
https://github.com/mirumee/saleor/issues/3250#issuecomment-442130475

**Comment by NyanKiyoshi** [comment]
Are you planning on handling this issue?

**Comment by jxltom** [comment]
Hey @NyanKiyoshi, I opened this as a reminder but I don't any specifc schedules on it. So please feel free to pick it up if  you would like to.

**Comment by NyanKiyoshi** [comment]
Alright! Just so I know!

I cannot until next week anyway.

But we still need to discuss how we want Saleor to behavior... @https://github.com/mirumee/saleor/issues/3567

**Comment by jxltom** [comment]
Fixed.
